name: Liquibase MySQL Setup

on:
    workflow_dispatch:  # Allows manual triggering

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_db
          MYSQL_DATABASE: liquibase_test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK (needed for Liquibase)
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Liquibase CLI
        run: |
          curl -L "https://github.com/liquibase/liquibase/releases/download/v4.30.0/liquibase-4.30.0.tar.gz" -o liquibase.tar.gz
           tar -xzvf liquibase.tar.gz
           sudo mkdir -p /opt/liquibase
           sudo mv * /opt/liquibase/
         
      - name: Download MySQL JDBC Driver
        run: |
            # Clean up any existing file
            rm -f /opt/liquibase/lib/mysql-connector-java-8.0.30.jar

            # Download the MySQL JDBC Connector with a retry and error check
            curl -fSL "https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar" -o /opt/liquibase/lib/mysql-connector-java-8.0.30.jar

            # Verify download is a JAR file
            if file /opt/liquibase/lib/mysql-connector-java-8.0.30.jar | grep -q "Java archive"; then
              echo "MySQL JDBC driver downloaded successfully."
            else
              echo "Download failed: file is not a valid JAR." >&2
              exit 1
            fi


      - name: Set Environment Variables for Liquibase
        run: |
          echo "LIQUIBASE_HOME=/opt/liquibase" >> $GITHUB_ENV
          echo "CLASSPATH=/opt/liquibase/lib/mysql-connector-java-8.0.32.jar" >> $GITHUB_ENV

      - name: Check if Liquibase is available
        run: $LIQUIBASE_HOME/liquibase --version

      - name: Run Liquibase update and check status
        run: |
          
          sudo find / -name "changelog.yml"
          echo $LIQUIBASE_HOME
          ls -l $LIQUIBASE_HOME
          echo $LIQUIBASE_HOME
          ls -l
          pwd
          git clone https://github.com/MR-7V/liquibase-poc2.git
          cd liquibase-poc2
          git checkout main
          cat $LIQUIBASE_HOME/changelog.yml
          $LIQUIBASE_HOME/liquibase --url="jdbc:mysql://34.121.133.153:3306/liquibase_test_db?user=root&password=test_db&connectTimeout=30000&socketTimeout=30000" \
          --username=mohith \
          --password=mohith \
          --changelog-file=changelog.yml update --logLevel=debug
